from fastapi import APIRouter, HTTPException
from fastapi.responses import HTMLResponse, RedirectResponse
from pydantic import BaseModel, Field

from backend.app.services.emotion_service import detect_emotion
from backend.app.services.music_service import (
    build_playlist,
    get_spotify_auth_url,
    handle_spotify_callback,
    save_playlist_to_spotify,
)

router = APIRouter(prefix="/api/music", tags=["music"])


class GeneratePlaylistRequest(BaseModel):
    text: str = Field(..., min_length=2, max_length=1000)


class SavePlaylistRequest(BaseModel):
    name: str = Field(..., min_length=1, max_length=120)
    description: str = Field(default="Generated by JKT Pulse", max_length=300)
    track_uris: list[str] = Field(default_factory=list)


@router.post("/generate-playlist")
def generate_playlist(payload: GeneratePlaylistRequest) -> dict:
    detected = detect_emotion(payload.text)
    playlist = build_playlist(detected["emotion"], detected["confidence"])

    return {
        "emotion": detected["emotion"],
        "confidence": detected["confidence"],
        "source": detected["source"],
        **playlist,
    }


@router.get("/login")
def spotify_login():
    try:
        return RedirectResponse(get_spotify_auth_url())
    except RuntimeError as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc


@router.get("/callback", response_class=HTMLResponse)
def spotify_callback(code: str):
    try:
        handle_spotify_callback(code)
    except RuntimeError as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc

    return """
    <html>
      <body style="font-family: system-ui; background: #101114; color: #f7f4ea; padding: 32px;">
        <h1>Spotify connected</h1>
        <p>You can return to JKT Pulse and save generated playlists.</p>
      </body>
    </html>
    """


@router.post("/save-playlist")
def save_playlist(payload: SavePlaylistRequest) -> dict:
    try:
        return save_playlist_to_spotify(payload.name, payload.description, payload.track_uris)
    except RuntimeError as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc
